### ISSUE TITLE
Register HClust.jl

### ISSUE THREAD

**Issue by tinybike** [davidavdav/HClust.jl#3]
Very nice work with this package!  If you think it's ready, would you mind registering it in https://github.com/JuliaLang/METADATA.jl?

(The reason I ask is because I'm using HClust.jl in https://github.com/AugurProject/Augur.jl.  I recently registered Augur.jl, and realized that it failing its automated tests because HClust.jl is not registered.)

**Comment by davidavdav** [comment]
Thanks for your message.

This is a painful process.  At the advice of the metadata maintainer i
included it into Clustering.jl where it was accepted after about half a
year...

So you could make your dependency on Clustering.jl instead. There still is
a small bug for small matrices for which i sent in a PR.

---david

sent from a mobile Linux os.
Op 10 jul. 2015 01:07 schreef "Jack Peterson" notifications@github.com:

**Comment by tinybike** [comment]
Got it.  Thank you for the heads-up, I will use the functions from Clustering.jl!
